### ISSUE TITLE
Composable function for displaying text 

### ISSUE THREAD

**Issue by Raidensama** [JuulLabs/sensortag#120]
##Hi, 
In the sensorChart function in SensorChart.kt I try to modify displaying but I can't use composable function to display text. I want to display values like this :

x = ??? 
y = ???
z = ???

I don't want to draw lines I want something more simple... Does somebody know how to do it ?

Regards

**Comment by twyatt** [comment]
Pre Compose, this SensorTag sample app actually did list the gyro values as you described.

Checkout ccdb556ed2e71214a45ee1b0b21a77b77faa9dd7 or browse https://github.com/JuulLabs/sensortag/tree/ccdb556ed2e71214a45ee1b0b21a77b77faa9dd7.

**Comment by Raidensama** [comment]
Ho I missed this version. I try this one and keep you updated.

Thank you

**Comment by Raidensama** [comment]
Hi

I tried to build this example but this time there are errors in the gradle 
![image](https://user-images.githubusercontent.com/31890986/175559215-626e8429-15bd-4fc8-b758-e26d3408c529.png)

![image](https://user-images.githubusercontent.com/31890986/175559508-e7d0c90b-5cdf-4e83-9d02-3d97d48c2a0e.png)

**Comment by twyatt** [comment]
Are you referring to the pre-Compose SHA? It is working for me...

```
git checkout ccdb556
./gradlew clean assembleDebug
```

```
BUILD SUCCESSFUL in 1m 23s
37 actionable tasks: 33 executed, 4 up-to-date
```

...or, are you referring to something else?

**Comment by Raidensama** [comment]
What do you mean when you say "Are you referring to the pre-Compose SHA? " I just donwloaded the android project and opened it in Android Studio and that's all. I think I don't understand this "referring" part... Can you explain please ?

**Comment by twyatt** [comment]
> when I write "git checkout [ccdb556](https://github.com/JuulLabs/sensortag/commit/ccdb556ed2e71214a45ee1b0b21a77b77faa9dd7)" it displays this "fatal: not a git repository (or any of the parent directories): .git"

You need to be on the SensorTag directory that you cloned, for example:

```zsh
git clone https://github.com/JuulLabs/sensortag.git
cd sensortag
git checkout ccdb556
```

**Comment by Raidensama** [comment]
Hello
Now I can build it succesfully thank you for your advice but when I try to run it on my smartphone I have this error "Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: Error loading build artifacts from..." I searched on google and some people said the gradle need to be update... So I tried but it didn't solve my problem. Do you have any idea ?

**Comment by twyatt** [comment]
> Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: Error loading build artifacts from...

Sorry, I've never seen that error. Not sure what else to try if bumping the Gradle version didn't help. 😢

**Comment by Raidensama** [comment]
Ok can you tell me which version do you choose for the gradle here ?

![image](https://user-images.githubusercontent.com/31890986/176641802-d0b40eb0-8635-427b-97b9-e5eaaf54132e.png)

Flie->Project Structure->Project

**Comment by twyatt** [comment]
Project is configured for Android Gradle Plugin (AGP) `7.2.1` on `main`.

https://github.com/JuulLabs/sensortag/blob/42f3907d1acbe998b2e4c6ca7d0cf627fe1a232c/gradle/libs.versions.toml#L3

If you're working under the previously mentioned ccdb556 commit, then it was `4.2.2` back then.
